# Generated by Django 5.0.4 on 2025-05-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0096_fingerprint_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_message', models.TextField()),
                ('due_date', models.DateField()),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
    ]
